import { Outlet,Link,createRootRoute,useRouter,HeadContent,Scripts } from "@tanstack/react-router";
import { useEffect,type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
function NotFoundComponent(){return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold tracking-tight text-foreground">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong on our end. You can try refreshing or head back home.</p><div className="mt-6 flex flex-wrap justify-center gap-2"><button onClick={()=>{router.invalidate();reset()}} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><a href="/" className="rounded-md border border-input px-4 py-2 text-sm">Go home</a></div></div></div>}
function MediaProtection(){useEffect(()=>{const isImageTarget=(target:EventTarget|null)=>target instanceof Element&&Boolean(target.closest("img"));const preventImageAction=(event:Event)=>{if(isImageTarget(event.target))event.preventDefault()};const preventShortcuts=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if((event.ctrlKey||event.metaKey)&&["s","u","p"].includes(key))event.preventDefault();if(event.key==="PrintScreen")event.preventDefault()};document.addEventListener("contextmenu",preventImageAction,true);document.addEventListener("dragstart",preventImageAction,true);document.addEventListener("selectstart",preventImageAction,true);document.addEventListener("keydown",preventShortcuts,true);return()=>{document.removeEventListener("contextmenu",preventImageAction,true);document.removeEventListener("dragstart",preventImageAction,true);document.removeEventListener("selectstart",preventImageAction,true);document.removeEventListener("keydown",preventShortcuts,true)}},[]);return null}
export const Route=createRootRoute({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"Torre de Pizza | Pizzaria artesanal em Campo Grande – RJ"},{name:"description",content:"Cardápio digital da Torre de Pizza: pizzas artesanais, combos e sobremesas com delivery, retirada e atendimento no local."},{name:"author",content:"Torre de Pizza"},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preload",href:"/hero-pizza.webp",as:"image",type:"image/webp"},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap"},{rel:"icon",type:"image/x-icon",href:"/favicon.ico"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt-BR"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){return <><MediaProtection/><Outlet/></>}
