/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel/index'
import { Route as PainelAdminRouteImport } from './routes/painel/admin'
import { Route as PainelPedidosRouteImport } from './routes/painel/pedidos'
import { Route as PainelMotoboyRouteImport } from './routes/painel/motoboy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/painel/',
  path: '/painel/',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/painel/admin',
  path: '/painel/admin',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelPedidosRoute = PainelPedidosRouteImport.update({
  id: '/painel/pedidos',
  path: '/painel/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)

const PainelMotoboyRoute = PainelMotoboyRouteImport.update({
  id: '/painel/motoboy',
  path: '/painel/motoboy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/painel': typeof PainelIndexRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/painel': typeof PainelIndexRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/painel/': typeof PainelIndexRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/pedidos': typeof PainelPedidosRoute
  '/painel/motoboy': typeof PainelMotoboyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/painel' | '/painel/admin' | '/painel/pedidos' | '/painel/motoboy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/painel' | '/painel/admin' | '/painel/pedidos' | '/painel/motoboy'
  id:
    | '__root__'
    | '/'
    | '/painel/'
    | '/painel/admin'
    | '/painel/pedidos'
    | '/painel/motoboy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelAdminRoute: typeof PainelAdminRoute
  PainelPedidosRoute: typeof PainelPedidosRoute
  PainelMotoboyRoute: typeof PainelMotoboyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/admin': {
      id: '/painel/admin'
      path: '/painel/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/pedidos': {
      id: '/painel/pedidos'
      path: '/painel/pedidos'
      fullPath: '/painel/pedidos'
      preLoaderRoute: typeof PainelPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/motoboy': {
      id: '/painel/motoboy'
      path: '/painel/motoboy'
      fullPath: '/painel/motoboy'
      preLoaderRoute: typeof PainelMotoboyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelAdminRoute: PainelAdminRoute,
  PainelPedidosRoute: PainelPedidosRoute,
  PainelMotoboyRoute: PainelMotoboyRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
